platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'HEAnalyticsExample'

pod 'GoogleAnalytics'
pod 'Mixpanel'
pod 'Flurry-iOS-SDK'
pod 'Intercom'
pod 'Localytics'
